### ISSUE TITLE
Find out about missing keys for retail firmwares

### ISSUE THREAD

**Issue by artart78** [John-K/pspdecrypt#11]
There are issues with :
- 5.05, 5.50, 5.51: expanded,error during decryption [tag 4c9420f0]. (10 modules)
- 5.55: expanded,error during decryption [tag 4c941af0] (87 times), [tag 4c941bf0] (10 times), [tag 4c9421f0] (10 times)
- 5.70 (fake PSAR): expanded,error during decryption [tag 4c941af0] (81 times), [tag 4c9421f0] (10 times)
- 6.10go: '00005' Cannot decrypt 5g table FFFFFFFF [tag C0A39A7A]. (everything fails afterwards so there could be other keys missing for the modules themselves)
- 6.20go: '00005' Cannot decrypt 5g table FFFFFFFF [tag A1C325FA]. (same as above)
- 6.39 testing tool: expanded,error during decryption [tag 4c9480f0] (93 times)

**Comment by artart78** [comment]
- 4c941af0 [*g] appears in 570go.PSAR/PSARDUMPER/reboot_05g.bin, 570go.PSAR/kd/memlmd_05g.prx, 555.PBP/PSARDUMPER/stage3_nandipl_01g.bin, 555.PBP/PSARDUMPER/stage3_nandipl_02g.ipl
- 4c941bf0 [02g only] appears in 555.PBP/PSARDUMPER/stage3_nandipl_02g.ipl
- 4c9420f0 [03g only] doesn't appear anywhere [might be in 03g IPL and reboot, which we can't have easily]
- 4c9421f0 [03g and 04g] doesn't appear anywhere [same as above]
- 4c9480f0 [*g] appears in 6.xx memlmd and 639_Testing_Tool_Revision_A.PBP/PSARDUMPER/stage3_nandipl_01g_ttool.bin

Which means 3 of them should be easy to add!

For the table issues with the tables, it looks like 610go and 620go don't use the same table DES key & IV (which means the "tags" I put above are not relevant btw). I have no idea where they're stored though.

**Comment by artart78** [comment]
- 4c941af0 and 4c9480f0 have been found
- the table issue has been fixed

So are still missing:
- 4c941bf0 [02g only] appears in 555.PBP/PSARDUMPER/stage3_nandipl_02g.ipl -> 02g keys have an additional obfuscation level which we'll have to solve
- 4c9420f0 [03g only] -> need to decrypt 03g+ from the stuff which just came out
- 4c9421f0 [03g and 04g] -> same

**Comment by John-K** [comment]
The remaining keys were added in #21, #18, #17
