### ISSUE TITLE
Merge pspdecrypt and psardecrypt, with additional arguments

### ISSUE THREAD

**Issue by artart78** [John-K/pspdecrypt#22]
Here's my proposal:
- pspdecrypt could take PBPs, PSARs and PSPs as an input
- `--outfile/-o` specifies the output decrypted PSP
- `--outdir/-O` specifies the output dir for PSAR
- `--extract-only` will only extract and not decrypt the PSAR's contents
- `--psar-only` and `--psp-only`, if given a PBP, will select what to extract/decrypt

Then, independently (using only `--outdir/-O`), `--ipl-decrypt` and a facultative `--preipl` argument.

Also, possibly, `--verbose` (at least for enabling the IPL decryption output).

It should cover #5 and #6

**Comment by John-K** [comment]
This sounds good to me. It would be nice to have it do something sane if you just passed it a file without any arguments too.

**Comment by WorldGenesis** [comment]
> 
> 
> This sounds good to me. It would be nice to have it do something sane if you just passed it a file without any arguments too.

It might be nice to have it show the PSAR/table version, and if its a FW update, show the update version too when run without arguments :P

**Comment by John-K** [comment]
That's a cool idea
