### ISSUE TITLE
stage2_psp_ipl.bin.gz

### ISSUE THREAD

**Issue by Yoti** [John-K/pspdecrypt#24]
Do we really need to keep GZ after successfully unpacking?

**Comment by artart78** [comment]
I thought it was cool to have it since there's date/filename metadata etc. Maybe it could just be put in the logs.

**Comment by krystalgamer** [comment]
I don't see no problem in keeping it tbh

**Comment by John-K** [comment]
Would probably be nice to not have both files there.

Another option would be to just not expand them and leave that to the user
